version: '3.3'
services:
  mysql:
    platform: linux/amd64
    image: library/mysql:5.7.32
    container_name: sp5_mysql
    command: "--sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' --default_authentication_plugin=mysql_native_password --character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"
    ports:
      - '3306:3306'
    networks:
      sp5-dev-local-network:
        ipv4_address: 10.6.1.2
    volumes:
      - subjectsplus5-db:/var/lib/mysql

  php-apache:
    platform: linux/amd64
    build:
      context: .docker/
      dockerfile: Dockerfile
      args:
        - ${XDEBUG_IDEKEY}
        - ${XDEBUG_REMOTE_PORT}
        - ${XDEBUG_REMOTE_HOST}
    container_name: sp5_php_apache
    restart: always
    ports:
      - 82:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - ${SUBJECTSPLUS_APP}:/home/site/wwwroot
      - .docker/config/mods-available/mpm_prefork.conf:/etc/apache2/mods-available/mpm_prefork.conf
    environment:
      - PHP_MEMORY_LIMIT=512M
    depends_on:
      - mysql
    networks:
      sp5-dev-local-network:
        ipv4_address: 10.6.1.3

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

# Name our volumes
volumes:
  subjectsplus5-db:
    driver: local

# Local virtual network
networks:
  sp5-dev-local-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "sp5-dockernet"
    ipam:
      config:
        - subnet: 10.6.1.0/16