services:
  mysql:
    platform: linux/amd64
    image: library/mysql:5.7.32
    container_name: "$MYSQL_CONTAINER_NAME"
    command: "--sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' --default_authentication_plugin=mysql_native_password --character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci"
    restart: always
    env_file:
      - .env.docker.calder.dev
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: "$MYSQL_DATABASE"
      MYSQL_USER: "$MYSQL_USER"
      MYSQL_PASSWORD: "$MYSQL_PASSWORD"
    ports:
      - "${MYSQL_CONTAINER_PORTS}"
    networks:
      calder-network:
        ipv4_address: 172.25.1.2
    volumes:
      - calder-subjectsplus5-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

  php-apache:
    platform: linux/arm64
    build:
      context: .docker/
      dockerfile: Dockerfile
      args:
        - "PHPSTORM"
        - "9003"
        - "host.docker.internal"
    container_name: "$PHP_APACHE_CONTAINER_NAME"
    restart: always
    env_file:
      - .env.docker.calder.dev
    ports:
      - "${PHP_APACHE_PORTS}"
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - ./SubjectsPlus:/home/site/wwwroot
      - .docker/config/mods-available/mpm_prefork.conf:/etc/apache2/mods-available/mpm_prefork.conf
    environment:
      - PHP_MEMORY_LIMIT=512M
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      calder-network:
        ipv4_address: 172.25.1.3

# Name our volumes
volumes:
  calder-subjectsplus5-db:
    driver: local

# Local virtual network
networks:
  calder-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16